services:
  backend:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db


  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ConecteDesafioDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
